blueprint:
  domain: automation
  name: Sonoff TRVZB External Sensor Sync
  description:
    "## Sonoff TRVZB External Temperature Sensor SYNCHRONISATION (v1.0.1 adapted by Dr_Bean)\nThis adapted
    blueprint synchronises the local temperature of one or more Sonoff TRVZBs with
    an external temperature sensor. Such behaviour might be required when an external
    temperature sensor more accurately reflects the room temperature compared with
    the internal temperature sensor in the TRV(s), or when you wish to use a single
    temperature sensor to control multiple radiators in a single room.\n\n
    When the sensor state is a valid number, the number.external_temperature_sensor_value
    of the TRVZB is updated and the switch.external_temperature_sensor is rewritten to external."
  input:
    sensor_entity:
      name: External Temperature Sensor
      description: The (single) entity of the external temperature sensor device
      selector:
        entity:
          filter:
            - domain:
                - sensor
              device_class:
                - temperature
          multiple: false
    trv_devices:
      name: Sonoff TRVZB(s)
      description: The entity of the Sonoff TRVZB device that represents the external temperature value.
      selector:
        entity:
          multiple: true
          filter:
            - domain: number
              device_class: temperature
triggers:
  - trigger: state
    entity_id: !input sensor_entity
  - trigger: time_pattern # added to keep trvzb from falling back to internal sensor
    minutes: /30
variables:
  external_sensor: !input sensor_entity
  trvs: !input trv_devices
conditions:
  - condition: template
    value_template: "{{ is_number(states(external_sensor)) }}"
actions:
  - action: number.set_value
    metadata: {}
    data:
      value: "{{ states(external_sensor) | float }}"
    target:
      entity_id: >-
        {%- set ns1 = namespace(ents=[]) -%}
        {%- for trv in trvs -%}
          {%- set matches = device_entities(trv)|select('search', 'external_temperature_sensor_value$')|list -%}
          {%- set ns1.ents = ns1.ents + matches -%}
        {%- endfor -%}
        {{- ns1.ents -}}
  - action: switch.turn_on
    metadata: {}
    data: {}
    target:
      entity_id: >-
        {%- set ns2 = namespace(ents=[]) -%}
        {%- for trv in trvs -%}
          {%- set matches = device_entities(trv)|select('search', 'external_temperature_sensor$')|list -%}
          {%- set ns2.ents = ns2.ents + matches -%}
        {%- endfor -%}
        {{- ns2.ents -}}
mode: single
